#page title
page_title                                : RollCall                                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 00000000                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link  : # Enter Google Play Store URL.
terms_link                                : https://rollcall.vote/terms/              # Terms and Conditions Link
beta_link                                 : https://rollcallvote2020.typeform.com/to/ywV8XGiL      #Link to Beta Test
presskit_download_link                    : https://www.notion.so/RollCall-vote-a97617632a0f418f9ad6c639e98c6dcc                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/circleicon.png                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : RollCall                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
# app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Working to make the 2020 US Elections fair and transparent for absentee/mail-in voters. Coming soon for iPhone and Android devices.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : RollCall                                
your_link                                 : https://rollcall.vote                   
your_city                                 : a bunch of different cities :heart:                              
email_address                             : rollcallvote2020@gmail.com
facebook_username                         : # none                                          
instagram_username                        : # none
twitter_username                          : rollcall_vote
github_username                           : # none
youtube_username                          : # none



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Make a plan to Vote.
    description                           : Whether you plan to vote by mail or in person, we'll help you find the details you need to make sure your ballot is counted.
    fontawesome_icon_name                 : question
    
  - title                                 : Let your local representatives know what's happening.
    description                           : Voter participation in Rollcall helps local election boards safely and securely get ahead of communities where ballots are not getting received or sent in time.
    fontawesome_icon_name                 : comments

  - title                                 : Track community engagement, together.
    description                           : Rollcall gives you insights into how your community is planning to vote, so that you can take specific steps to increase turnout and impact.
    fontawesome_icon_name                 : poll

  - title                                 : #
    description                           : #
    fontawesome_icon_name                 : #

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/tiffany-tertipes-x0OXe9xEIL4-unsplash.jpg                 # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#4D5ACE"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
